### ISSUE TITLE
Can't use angular-ra-newrelic with atomify/browserify + minifiy

### ISSUE THREAD

**Issue by ashleahhill** [red-ant/angular-ra-pageload#2]
I am using angular-ra-newrelic within a project that uses Atomify to manage our dependencies. Because angular-ra-newrelic and angular-ra-pageload use implicit annotation instead of inline array notation for injected dependencies, minifying the code breaks the app.

Would it be possible to use inline array annotation so that the module can be bundled and minified?

Also posted in red-ant/angular-ra-newrelic#1

**Comment by jsntv200** [comment]
Thanks...  v0.1.1 fixes the grunt task to annotate the un-minified js
